### ISSUE TITLE
Sprockets::EncodingError

### ISSUE THREAD

**Issue by andreacfm** [johnbintz/jasmine-headless-webkit#117]
Using 0.0.9rc1.
If I do not export LANG I get this error:

``` ruby
[jasmine-headless-webkit] /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/vendor/assets/javascripts/beautify-html.js has a invalid US-ASCII byte sequence (Sprockets::EncodingError)
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/utils.rb:18:in `block in read_unicode'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/utils.rb:12:in `tap'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/utils.rb:12:in `read_unicode'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/context.rb:171:in `evaluate'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/processed_asset.rb:12:in `initialize'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `new'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `block in build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:262:in `circular_call_protection'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:240:in `build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:89:in `block in build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/caching.rb:12:in `cache_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:244:in `new'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:244:in `build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:89:in `block in build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/caching.rb:12:in `cache_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/sprockets-2.1.2/lib/sprockets/environment.rb:74:in `find_asset'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/files_list.rb:265:in `add_path'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/files_list.rb:106:in `block in load_initial_assets'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/files_list.rb:104:in `each'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/files_list.rb:104:in `load_initial_assets'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/files_list.rb:98:in `initialize'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/runner.rb:235:in `new'
  /Users/andrea/.rvm/gems/ruby-1.9.2-p180-patched/gems/jasmine-headless-webkit-0.9.0.rc1/lib/jasmine/headless/runner.rb:235:in `files
```

**Comment by gicappa** [comment]
+1

**Comment by sidonath** [comment]
+1

@andreacfm thanks for mentioning `export LANG=UTF-8` workaround :)
