### ISSUE TITLE
Windows problem with coffeescript compilation

### ISSUE THREAD

**Issue by nhajratw** [johnbintz/jasmine-headless-webkit#119]
Using revision 453f4392714adaae3891a6f5103d74b2dd2e5c58 of JHW, we were able to get it _installed_ on windows.

However, we are now getting this error. (works fine on the mac, btw) It looks like it might just be a file path handling problem.

Any ideas?

```
C:\work>jasmine-headless-webkit -j jasmine.yml
[coffeescript] Error in compiling file: C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/jasmine-extensions.coffee
[jasmine-headless-webkit] Invalid argument - C:/work/.jhw-cache/coffee_script/C:
  (in C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/vendor/assets/javascripts/jasmine-extensions.coffee) (Errno::EINVAL)
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:205:in `each'
  C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/cacheable_action.rb:47:in `handle'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/coffee_template.rb:19:in `evaluate'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/context.rb:193:in `block in evaluate'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/context.rb:190:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/context.rb:190:in `evaluate'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/processed_asset.rb:12:in `initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/base.rb:249:in `new'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/base.rb:249:in `block in build_asset'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sprockets-2.3.1/lib/sprockets/base.rb:270:
```

**Comment by mtanji** [comment]
Hi johnbintz,

Using 1.3.0 of JHW, I have got the same issue that nhajratw had one year ago regarding ivalid file path arguments.

Any ideas of what should be done to fix it?

```
C:\Ruby200\lib\ruby\gems\2.0.0\gems\jasmine-1.3.0\generators\jasmine\templates\spec\javascripts\support>jasmine-headless-webkit -j jasmine.yml
[coffeescript] Error in compiling file: C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/vendor/assets/javascripts/jasmine-exten
sions.coffee
[jasmine-headless-webkit] Invalid argument - C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-1.3.0/generators/jasmine/templates/spec/javascripts/support/.
jhw-cache/coffee_script/C:
  (in C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/vendor/assets/javascripts/jasmine-extensions.coffee) (Errno::EINVAL)
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:323:in `mkdir'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:323:in `fu_mkdir'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:298:in `block (2 levels) in mkdir_p'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:296:in `reverse_each'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:296:in `block in mkdir_p'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:282:in `each'
  C:/Ruby200/lib/ruby/2.0.0/fileutils.rb:282:in `mkdir_p'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/cacheable_action.rb:47:in `handle'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/coffee_template.rb:19:in `evaluate'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/tilt-1.3.5/lib/tilt/template.rb:77:in `render'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/context.rb:197:in `block in evaluate'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/context.rb:194:in `each'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/context.rb:194:in `evaluate'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/processed_asset.rb:12:in `initialize'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:374:in `new'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:374:in `block in build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:395:in `circular_call_protection'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:373:in `build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:94:in `block in build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/caching.rb:51:in `cache_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:93:in `build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:287:in `find_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:61:in `find_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:377:in `new'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:377:in `build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:94:in `block in build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/caching.rb:51:in `cache_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:93:in `build_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/base.rb:287:in `find_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/index.rb:61:in `find_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.8.2/lib/sprockets/environment.rb:75:in `find_asset'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/files_list.rb:273:in `add_path'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/files_list.rb:100:in `block in load_initial_assets'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/files_list.rb:98:in `each'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/files_list.rb:98:in `load_initial_assets'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/files_list.rb:84:in `initialize'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/runner.rb:235:in `new'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/runner.rb:235:in `files_list'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/template_writer.rb:21:in `write'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/runner.rb:188:in `run'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/lib/jasmine/headless/command_line.rb:18:in `run!'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/jasmine-headless-webkit-0.9.0.rc.2/bin/jasmine-headless-webkit:10:in `<top (required)>'
  C:/Ruby200/bin/jasmine-headless-webkit:23:in `load'
  C:/Ruby200/bin/jasmine-headless-webkit:23:in `<main>'
```
