### ISSUE TITLE
Windows 7 - "which gmake" error

### ISSUE THREAD

**Issue by andrewwakeling** [johnbintz/jasmine-headless-webkit#158]
I have installed QtSDK, Ruby 1.9.3 + DevKit.

I managed to run "gem install jasmine-headless-webkit".

When I attempt to run it, I get the following error:

C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:97:in ``': No such file or directory - which gmake (Errno::ENOENT)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:97:in`get_exe_path'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:53:in `make_path'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:16:in`make_installed?'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:103:in `check_make!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/qt/qmake.rb:37:in`make!'
        from extconf.rb:8:in `<main>'
[jasmine-headless-webkit] The jasmine-headless-webkit specrunner (jasmine-webkit-specrunner) could not be found! Try reinstalling the gem. (Jasmine::Headless::N
oRunnerError)
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/runner.rb:41:in`initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in `new'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in`run!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/bin/jasmine-headless-webkit:10:in `<top (required)>'
  C:/Ruby193/bin/jasmine-headless-webkit:23:in`load'
  C:/Ruby193/bin/jasmine-headless-webkit:23:in `<main>'

Looking at the code in \jasmine-headless-webkit-0.8.4\lib\qt\qmake.rb, it searches for "gmake" using "which".

Am I supposed to have make/gmake installed in Windows?
Am I supposed to have a "which" command tool available?

**Comment by tommyk** [comment]
Is there a fix for this?  I have run into the same thing...

**Comment by ghost** [comment]
That makes 3 of us. Still trying to figure out how to get around this.

**Comment by ghost** [comment]
Actually, I finally have a solve for this. Install QT and make sure you have the install folder /bin in your PATH and viola!
