### ISSUE TITLE
Unrecognized option `--use-server'

### ISSUE THREAD

**Issue by alvarezloaiciga** [johnbintz/jasmine-headless-webkit#174]
Hey!.
I am running ' jasmine-headless-webkit --use-server ' but it is failing. This is the backtrace:

[jasmine-headless-webkit] unrecognized option `--use-server' (GetoptLong::InvalidOption)
  /Users/alvarezloaiciga/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/getoptlong.rb:394:in`set_error'
  /Users/alvarezloaiciga/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/getoptlong.rb:501:in `get'
  /Users/alvarezloaiciga/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/getoptlong.rb:602:in`block in each'
  /Users/alvarezloaiciga/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/getoptlong.rb:601:in `loop'
  /Users/alvarezloaiciga/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/getoptlong.rb:601:in`each'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/options.rb:93:in `process_command_line_args'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/options.rb:28:in`from_command_line'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:9:in `run!'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/gems/jasmine-headless-webkit-0.8.4/bin/jasmine-headless-webkit:10:in`<top (required)>'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/bin/jasmine-headless-webkit:19:in `load'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/bin/jasmine-headless-webkit:19:in`<main>'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/alvarezloaiciga/.rvm/gems/ruby-1.9.3-p194@Givers_And_Needers/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by sdizier** [comment]
+1

**Comment by rymohr** [comment]
+1

**Comment by settinghead** [comment]
+1
