### ISSUE TITLE
No runner found, attempting to compile / DEBIAN

### ISSUE THREAD

**Issue by greyblake** [johnbintz/jasmine-headless-webkit#180]
# Description

It might look like #80, but I use Qt 4.8.2.

Attempt to run `jasmine-headless-webkit`  fails with the next error message:

```
$ jasmine-headless-webkit 

No runner found, attempting to compile...
make: *** No rule to make target `clean'.  Stop.
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -o specrunner.o specrunner.cpp
specrunner.cpp: In function ‘int main(int, char**)’:
specrunner.cpp:37:39: error: ‘getopt’ was not declared in this scope
specrunner.cpp:43:20: error: ‘optarg’ was not declared in this scope
specrunner.cpp:48:7: error: ‘optind’ was not declared in this scope
specrunner.cpp:61:16: error: ‘optind’ was not declared in this scope
make: *** [specrunner.o] Error 1
[jasmine-headless-webkit] The jasmine-headless-webkit specrunner (jasmine-webkit-specrunner) could not be found! Try reinstalling the gem. (Jasmine::Headless::NoRunnerError)
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/runner.rb:41:in `initialize'
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in `new'
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/gems/jasmine-headless-webkit-0.8.4/lib/jasmine/headless/command_line.rb:10:in `run!'
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/gems/jasmine-headless-webkit-0.8.4/bin/jasmine-headless-webkit:10
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/bin/jasmine-headless-webkit:19:in `load'
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/bin/jasmine-headless-webkit:19
  /home/spotapov/.rvm/gems/ree-1.8.7-2012.02@agent_portal/bin/ruby_noexec_wrapper:14
```
# Environment
### OS

Linux, Debian Wheezy

```
uname -a
Linux ws-41 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2 x86_64 GNU/Linux
```
### Packages

Qt packages are installed:

```
$ dpkg -l | egrep 'libqt4-dev|qt4-qmake'
ii  libqt4-dev                            4:4.8.2+dfsg-11                    amd64        Qt 4 development files
ii  libqt4-dev-bin                        4:4.8.2+dfsg-11                    amd64        Qt 4 development programs
ii  qt4-qmake                             4:4.8.2+dfsg-11                    amd64        Qt 4 qmake Makefile generator tool
```
### Qt / qmake versions

```
qmake-qt4 -v
QMake version 2.01a
Using Qt version 4.8.2 in /usr/lib/x86_64-linux-gnu
```

```
qmake -v
QMake version 2.01a
Using Qt version 4.8.2 in /usr/lib/x86_64-linux-gnu
```
### Ruby / Rails

```
ruby -v
ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2012.02
```

Rails 3.2.12

**Comment by dzhlobo** [comment]
I have the same problem with the same versions of qmake, libqt4 and rails:

```
No runner found, attempting to compile...
make: *** No rule to make target `clean'.  Stop.
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -o specrunner.o specrunner.cpp
specrunner.cpp: In function ‘int main(int, char**)’:
specrunner.cpp:37:39: error: ‘getopt’ was not declared in this scope
specrunner.cpp:43:20: error: ‘optarg’ was not declared in this scope
specrunner.cpp:48:7: error: ‘optind’ was not declared in this scope
specrunner.cpp:61:16: error: ‘optind’ was not declared in this scope
make: *** [specrunner.o] Error 1
```

My environment is:

``` bash
ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]

rails -v
Rails 3.2.12

qmake -v
QMake version 2.01a
Using Qt version 4.8.3 in /usr/lib/x86_64-linux-gnu

dpkg -l | egrep 'libqt4-dev|qt4-qmake'
ii  libqt4-dev                                      4:4.8.3+dfsg-0ubuntu3.1                   amd64        Qt 4 development files
ii  libqt4-dev-bin                                  4:4.8.3+dfsg-0ubuntu3.1                   amd64        Qt 4 development programs
ii  qt4-qmake                                       4:4.8.3+dfsg-0ubuntu3.1                   amd64        Qt 4 qmake Makefile generator tool
```

**Comment by greyblake** [comment]
@Proghat I'm glad to know I'm not the one :D

**Comment by baburdick** [comment]
+1

**Comment by klacointe** [comment]
+1

**Comment by rwestgeest** [comment]
+1 (Ubuntu 12.10)

**Comment by adisuryadi** [comment]
also happens on my Ubuntu 13.04 Machine.

```
Linux ring-01 3.8.0-23-generic #34-Ubuntu SMP Wed May 29 20:22:58 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
QMake version 2.01a
Using Qt version 4.8.4 in /usr/lib/x86_64-linux-gnu

guard-jasmine-headless-webkit (0.3.2)
guard (1.8.0)
jasmine-headless-webkit (0.8.4)
jasmine-core (1.3.1)
```

**Comment by adisuryadi** [comment]
I think this pull request https://github.com/johnbintz/jasmine-headless-webkit/pull/177 fix this, and already merged to master. 
I changed the line in my Gemfile to use Github master branch instead, then it work just fine.

``` ruby
gem 'jasmine-headless-webkit', :git => 'https://github.com/johnbintz/jasmine-headless-webkit.git', branch: 'master'
```
