### ISSUE TITLE
Windows 7 Installation Failures

### ISSUE THREAD

**Issue by colin-jack** [johnbintz/jasmine-headless-webkit#59]
I installed QT using installer from http://qt.nokia.com/downloads.

All went fine, I then included 'jasmine-headless-webkit' in my gemfile but bunder then gave me errors:

 C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:552:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    C:/Ruby192/bin/ruby.exe extconf.rb 
```

C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:85:in ``': No such file or directory - which gmake (Errno::ENOENT)
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:85:in`get_exe_path'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:49:in `make_path'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:17:in`make_installed?'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:91:in `check_make!'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.6.3/lib/qt/qmake.rb:34:in`make!'
    from extconf.rb:7:in `<main>'

I was wondering if anyone had encountered similiar issues?

**Comment by johnbintz** [comment]
Heh, I was just talking with a coworker about this today, right before you posted this. :) I have barely any experience with modern Ruby development on Windows, but I do have Windows 7 sitting on a VM nearby. So the first question is: what way did you use to install Ruby on Windows? RubyInstaller?

**Comment by colin-jack** [comment]
Sorry I thought I'd replied but it didn't seem to have come through. 

Yup I've used that in the past and didn't have any issues, more recently I've been using RubyMine which handles it.

**Comment by johnbintz** [comment]
So my VM is not in any state to do anything with this for quite a while. :( I'll put out a call for assistance on Twitter.

**Comment by nhajratw** [comment]
Installed QT 4.7.3, Ruby 1.9.3 + DevKit, Windows 7

something wrong with mkspecs?

This is the current error I'm getting:

```
c:\work> gem install jasmine-headless-webkit

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing jasmine-headless-webkit:
        ERROR: Failed to build gem native extension.

        C:/Ruby193/bin/ruby.exe extconf.rb
make: *** No rule to make target `clean'.  Stop.
Could not find mkspecs for your QMAKESPEC(specrunner.pro) after trying:
        C:\QtSDK\Desktop\Qt\4.7.3\mingw\\mkspecs
Error processing project file: C:/Ruby193/lib/ruby/gems/1.9.1/gems/jasmine-headless-webkit-0.8.4/ext/jasmine-webkit-specrunner/jasmine-webkit-specrunner.pro
make: *** No targets specified and no makefile found.  Stop.

make
true
process_begin: CreateProcess(NULL, true, ...) failed.
make (e=2): The system cannot find the file specified.

make: *** [build] Error 2
```

**Comment by johnbintz** [comment]
What's in that mingw/mkspecs directory, out of curiosity?

**Comment by nhajratw** [comment]
FWIW - we were able to get it installed by using revision 453f4392714adaae3891a6f5103d74b2dd2e5c58

However, we're now getting the error described in https://github.com/johnbintz/jasmine-headless-webkit/issues/119

**Comment by nhajratw** [comment]
also FWIW -- here is the contents of mingw/mkspecs

```
C:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs>dir
 Volume in drive C is C-Drive
 Volume Serial Number is 10D1-1CCC

 Directory of C:\QtSDK\Desktop\Qt\4.7.3\mingw\mkspecs

02/15/2012  08:46 PM    <DIR>          .
02/15/2012  08:46 PM    <DIR>          ..
02/15/2012  08:46 PM    <DIR>          aix-g++
02/15/2012  08:46 PM    <DIR>          aix-g++-64
02/15/2012  08:46 PM    <DIR>          aix-xlc
02/15/2012  08:46 PM    <DIR>          aix-xlc-64
02/15/2012  08:46 PM    <DIR>          common
02/15/2012  08:46 PM    <DIR>          cygwin-g++
02/15/2012  08:46 PM    <DIR>          darwin-g++
02/15/2012  08:56 PM    <DIR>          default
02/15/2012  08:46 PM    <DIR>          features
02/15/2012  08:46 PM    <DIR>          freebsd-g++
02/15/2012  08:46 PM    <DIR>          freebsd-g++34
02/15/2012  08:46 PM    <DIR>          freebsd-g++40
02/15/2012  08:46 PM    <DIR>          freebsd-icc
02/15/2012  08:46 PM    <DIR>          hpux-acc
02/15/2012  08:46 PM    <DIR>          hpux-acc-64
02/15/2012  08:46 PM    <DIR>          hpux-acc-o64
02/15/2012  08:46 PM    <DIR>          hpux-g++
02/15/2012  08:46 PM    <DIR>          hpux-g++-64
02/15/2012  08:46 PM    <DIR>          hpuxi-acc-32
02/15/2012  08:46 PM    <DIR>          hpuxi-acc-64
02/15/2012  08:46 PM    <DIR>          hpuxi-g++-64
02/15/2012  08:46 PM    <DIR>          hurd-g++
02/15/2012  08:46 PM    <DIR>          irix-cc
02/15/2012  08:46 PM    <DIR>          irix-cc-64
02/15/2012  08:46 PM    <DIR>          irix-g++
02/15/2012  08:46 PM    <DIR>          irix-g++-64
02/15/2012  08:46 PM    <DIR>          linux-cxx
02/15/2012  08:46 PM    <DIR>          linux-ecc-64
02/15/2012  08:46 PM    <DIR>          linux-g++
02/15/2012  08:46 PM    <DIR>          linux-g++-32
02/15/2012  08:46 PM    <DIR>          linux-g++-64
02/15/2012  08:46 PM    <DIR>          linux-g++-maemo
02/15/2012  08:46 PM    <DIR>          linux-icc
02/15/2012  08:46 PM    <DIR>          linux-icc-32
02/15/2012  08:46 PM    <DIR>          linux-icc-64
02/15/2012  08:46 PM    <DIR>          linux-kcc
02/15/2012  08:46 PM    <DIR>          linux-llvm
02/15/2012  08:46 PM    <DIR>          linux-lsb-g++
02/15/2012  08:46 PM    <DIR>          linux-pgcc
02/15/2012  08:46 PM    <DIR>          lynxos-g++
02/15/2012  08:46 PM    <DIR>          macx-g++
02/15/2012  08:46 PM    <DIR>          macx-g++40
02/15/2012  08:46 PM    <DIR>          macx-g++42
02/15/2012  08:46 PM    <DIR>          macx-icc
02/15/2012  08:46 PM    <DIR>          macx-llvm
02/15/2012  08:46 PM    <DIR>          macx-pbuilder
02/15/2012  08:46 PM    <DIR>          macx-xcode
02/15/2012  08:46 PM    <DIR>          macx-xlc
02/15/2012  08:46 PM    <DIR>          modules
02/15/2012  08:46 PM    <DIR>          netbsd-g++
02/15/2012  08:46 PM    <DIR>          openbsd-g++
02/15/2012  08:46 PM               562 qconfig.pri
02/15/2012  08:46 PM    <DIR>          qws
02/15/2012  08:46 PM    <DIR>          sco-cc
02/15/2012  08:46 PM    <DIR>          sco-g++
02/15/2012  08:46 PM    <DIR>          solaris-cc
02/15/2012  08:46 PM    <DIR>          solaris-cc-64
02/15/2012  08:46 PM    <DIR>          solaris-cc-64-stlport
02/15/2012  08:46 PM    <DIR>          solaris-cc-stlport
02/15/2012  08:46 PM    <DIR>          solaris-g++
02/15/2012  08:46 PM    <DIR>          solaris-g++-64
02/15/2012  08:46 PM    <DIR>          symbian
02/15/2012  08:46 PM    <DIR>          symbian-abld
02/15/2012  08:46 PM    <DIR>          symbian-sbsv2
02/15/2012  08:46 PM    <DIR>          tru64-cxx
02/15/2012  08:46 PM    <DIR>          tru64-g++
02/15/2012  08:46 PM    <DIR>          unixware-cc
02/15/2012  08:46 PM    <DIR>          unixware-g++
02/15/2012  08:46 PM    <DIR>          unsupported
02/15/2012  08:46 PM    <DIR>          win32-borland
02/15/2012  08:46 PM    <DIR>          win32-g++
02/15/2012  08:46 PM    <DIR>          win32-icc
02/15/2012  08:46 PM    <DIR>          win32-msvc2003
02/15/2012  08:46 PM    <DIR>          win32-msvc2005
02/15/2012  08:46 PM    <DIR>          win32-msvc2008
02/15/2012  08:46 PM    <DIR>          win32-msvc2010
02/15/2012  08:46 PM    <DIR>          wince50standard-armv4i-msvc2005
02/15/2012  08:46 PM    <DIR>          wince50standard-armv4i-msvc2008
02/15/2012  08:46 PM    <DIR>          wince50standard-mipsii-msvc2005
02/15/2012  08:46 PM    <DIR>          wince50standard-mipsii-msvc2008
02/15/2012  08:46 PM    <DIR>          wince50standard-mipsiv-msvc2005
02/15/2012  08:46 PM    <DIR>          wince50standard-mipsiv-msvc2008
02/15/2012  08:46 PM    <DIR>          wince50standard-sh4-msvc2005
02/15/2012  08:46 PM    <DIR>          wince50standard-sh4-msvc2008
02/15/2012  08:46 PM    <DIR>          wince50standard-x86-msvc2005
02/15/2012  08:46 PM    <DIR>          wince50standard-x86-msvc2008
02/15/2012  08:46 PM    <DIR>          wince60standard-armv4i-msvc2005
02/15/2012  08:46 PM    <DIR>          wince60standard-x86-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm50pocket-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm50pocket-msvc2008
02/15/2012  08:46 PM    <DIR>          wincewm50smart-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm50smart-msvc2008
02/15/2012  08:46 PM    <DIR>          wincewm60professional-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm60professional-msvc2008
02/15/2012  08:46 PM    <DIR>          wincewm60standard-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm60standard-msvc2008
02/15/2012  08:46 PM    <DIR>          wincewm65professional-msvc2005
02/15/2012  08:46 PM    <DIR>          wincewm65professional-msvc2008
```

**Comment by johnbintz** [comment]
I would try setting an environment variable for QMAKESPEC (if you haven't already done so): http://www.qtforum.org/article/28116/installing-qt-4-5-2-on-windows.html

I'm committing a change that that doesn't specify the QMAKESPEC. See if that also helps.
