### ISSUE TITLE
Could not find jasmine-headless-webkit (>= 0)

### ISSUE THREAD

**Issue by risingspiral** [johnbintz/jasmine-headless-webkit#96]
I'm a ruby n00b and not sure what this is telling me. It looks like it can't find the jasmine-headless-webkit gem amongst a subset of gems installed. I'm not sure where it's getting this list.

When attempting to run jasmine-headless-webkit I get the following error:

[eanderson@dev jsmn-pg]$ sudo jasmine-headless-webkit
/usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find jasmine-headless-webkit (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /usr/local/rvm/gems/ruby-1.9.3-p0/bin/jasmine-headless-webkit:18:in`<main>'

Any help or insight anyone could provide would be appricated.

Thanks,

Eric

**Comment by risingspiral** [comment]
Nevermind. Invoking the call without sudo works.
